### ISSUE TITLE
[FEATURE] -improve template context

### ISSUE THREAD

**Issue by oknozor** [oknozor/toml-bombadil#209]
**Is your feature request related to a problem? Please describe.**
While the current template system works it feels a bit messy. 

The template context is updated using a `Hashmap<String, String>` , merging values from sub profiles in the global context. 

### Current templating system 

We have a global variable file enabled in `bombadil.toml`
```toml
# File: dotfiles/bombadil.toml
[settings]
vars = [ "vars/vars.toml"  ]
```
Containing the following variables: 

```toml
# File: dotfiles/vars/vars.toml
wallpaper = "$HOME/dotfiles/wallpapers/sea.jpg"
terminal = "alacritty"
```
We can overwrite `wallpaper` using an additional profile 
```toml
# File: dotfiles/vars/themes/home.toml
wallpaper = "~/dotfiles/assets/wallpapers/night_sky_34i.jpg"
```

This works fine as long as we don't shallow a variable twice. 
Currently it's hard to predict the final value of a variable when  shallowing it multiple time in different profiles.

**Describe the solution you'd like**
tera allow to pass `serde_json::Value` in its context. 
This would allow to write variable using all the toml semantic in a more structured way. 

### Example
```toml
# dotfiles/vars.toml
[colors]
blue = "#blue"
red = "#red"

[secrets]
passphrase = "some gpg encrypted value" 

[desktop.sway]
bar = "ironbar"
login_manager = "gtk-greet"

# or toml objects
desktop = [
  { i3 = { bar = "polybar", login_manager = "gdm"  } }
]

# ...etc
```

The following approach as several advantages : 
- enable to write structured variables context for dotfiles template and eliminate some off the mental load currently required to remember which variables file is loaded were etc.
- Enable better templating experience
  ```
  .class {
      {%- if profiles is containing("fancy") -%}
      color: {{red}}
      {%- else -%}
      color: {{black}}
      {%- endif -%}
   }
   ```
- We could provide some default context like `os`, `profiles`, `locale` etc.
