### ISSUE TITLE
[FEATURE] Allow using standard directories

### ISSUE THREAD

**Issue by flying-sheep** [oknozor/toml-bombadil#258]
**Is your feature request related to a problem? Please describe.**
Same problem as in #229: some applications use OS standard directories as explained in the [`directories` crate][]’s docs

**Describe the solution you'd like**
- If not already possible (didn’t see it in the docs) allow using variables in `{settings,profiles.*}.dots.*.target`
- pre-define variables for standard directories as exposed by the [`directories` crate][].

With this, the problem described in #229 would be as easy as:

```toml
[settings.dots]
vscode = { source = "editor/vscode.json", target = "%config_dir/Code/User/settings.json" }
```

**Describe alternatives you've considered**
#229 or a way to programmatically define profiles/variables

[`directories` crate]: https://crates.io/crates/directories
