### ISSUE TITLE
Bug: linking does not keep file permissions

### ISSUE THREAD

**Issue by lucas-dclrcq** [oknozor/toml-bombadil#31]
I use bombadil to link a script with execution permissions, because the symbolic link is based on the copy of the file with variables replaced it does not have execution permisssions.

**Comment by oknozor** [comment]
fixed in caea5d will be released with #24 

Do we need to specify permissions in the config like so ? 
```toml 
[settings.dots]
ssh = { source = "ssh", target = ".ssh", permissions = 700 } 
```
