### ISSUE TITLE
[FEATURE] - Add regex support in import paths

### ISSUE THREAD

**Issue by oknozor** [oknozor/toml-bombadil#32]
Importing is currently done this way : 
```toml
[[import]]
path = 'path/to/imported-config.toml` 
```

The `path` property only supports path to a file. Users shall be able to import multiple files using a regex or a directory path : 

```toml
[[import]]
path = 'path/to/config_dir/*.toml` 
```

```toml
[[import]]
path = 'path/to/config_dir/**
```
