### ISSUE TITLE
[BUG] Variable override using profiles doesn't override default vars.toml values

### ISSUE THREAD

**Issue by Rasmus-Bertell** [oknozor/toml-bombadil#395]
**Describe the bug**

[Variable override](https://oknozor.github.io/toml-bombadil/guide/profiles.html#variable-overrides) seems to not work as expected. I defined a similar setup for my dotfiles.

```toml
# bombadil.toml
dotfiles_dir = "Projects/dotfiles"
gpg_user_id  = "rasmus@bertell.fi"

[settings]
vars = [ "vars.toml" ]

[settings.dots.git]
source = "git"
target = ".config/git"

# ...

[profiles.work]
vars = [ "work.toml" ]
```

```toml
# vars.toml
[system]
terminal = "Ghostty"

# ...
```

```toml
# work.toml
[system]
terminal = "Windows Terminal"

# ...
```

**To Reproduce**

After running `bombadil link --profiles work` the templates have terminal as `Ghostty` instead of `Windows Terminal`. Running `bombadil get vars work` shows the correct variables.

**Expected behavior**

I expected the terminal value in system to be 'Windows Terminal' because that is what is defined in the work profile.

**Additional context**

If I rename `vars.toml` to something else then the profiles seem to work as expected. I think it has something to do with [variable co-location](https://oknozor.github.io/toml-bombadil/guide/templates.html#variable-co-location)

**Environment**

- Bombadil version: 4.2.0
- OS: Arch Linux WSL
