### ISSUE TITLE
[FEATURE] Extra Profiles

### ISSUE THREAD

**Issue by TravisDavis-ops** [oknozor/toml-bombadil#60]
## Why
I have been using profiles a lot to organize  my dots on multiple machines, so it has become very tideous to try and remember which profiles I need on which machines

## What is it
So I was think it would be nice to have some sort of system very similar to cargos feature flags where you have a single flag enable other flags

### The config file

```toml
[settings]
vars = ["default_colors.toml"]
extra-profiles = ["shell"]

[profiles.nord]
extra-profiles = ["shell", "sway"]
vars = ["colors.toml"]

[profiles.shell.dots]
fish = {...}
ranger = {...}

[profiles.sway]
prehooks = ["pkill waybar"]
posthooks = ["sway reload"]

[profiles.sway.dots]
waybar-top  = {....}
waybar-bottom = {...}
sway = {...}
```

So with this config you should be able to 
`bombadil link` should also enable shell + defaults
`bombadil link -p shell` should do the same thing 
`bombadil link -p nord`   should enable enable shell and sway and nord  + defaults
